security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: 11labs, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: _security_check
                login_path: _login
            logout:
                path:   _logout
                target: home

    access_control:
        - { path: ^/_(wdt|profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bundles*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/login$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/secured/article, roles: ROLE_ADMIN }
